norm = {' yg ':' yang ',
	    ' ganjar ':' ', 
	    'ganjar ':' ',
        ' anies ':' ',
	    'anies ':' ', 
	    ' gibran ':' ',
	    'gibran ':' ',
        ' muhaimin ':' ',
	    'muhaimin ':' ',	
	    ' mahfud ':' ',
	    'mahfud ':' ',
        ' cak imin ':' ',
	    'cak imin ':' ',
	    ' prabowo ':' ',
        'prabowo ':' ',
        ' bru ':' baru ', 
	    ' nggak ':' tidak ',
        ' gak ':' tidak ',
        ' gk ':' tidak ', 
	    ' ngga ':' tidak ',
        ' ga ':' tidak ',
        ' engga ':' tidak', 
	    ' pa ':' pak ',
        ' gaada ':' tidak ada ', 
	    ' thn ':' tahun ',
        ' udah ':' sudah ', 
	    ' udh ':' sudah ',
        ' nipu ':' tipu ',
        ' belom ':' belum ', 
	    ' mantab ':' keren ',
        ' kyk ':' seperti ',
        ' ky ':' seperti ',
        ' tpi ':' tapi ',
        ' krn ': ' karena ',
        ' alesan ':' alasan ',
        ' kasi ':' beri ',
        ' cakep ':' rupawan ',
        ' bener ':' benar ',
        ' rada ':' sedikit ',
        ' msh ':' masih ',
        ' napa ':' kenapa ',
        ' knp ':' kenapa ',
        ' legowo ':' ikhlas ',
        ' klo ':' kalau ',
        ' tdk ':' tidak ',
        ' gw ':' saya ',
        ' jg ':' juga',
        ' sama2 ':' sama sama',
        ' jdi ':' jadi ',
        ' smpai ':' sampai ',
        ' tak ': ' tidak ',
        ' banget ':' sangat ',
        ' ngerti ':' mengerti ',
        ' gabisa ':' tidak bisa ',
        ' sampe ':' sampai ',
        ' spy ':' supaya ',
        ' emang ':' memang ',
        ' emg ':' memang ',
        'emg ':' memang ',
        ' ama ':' sama ',
        ' gimana':' ',
        ' mrk ':' mereka ',
        ' jgn ':' jangan ',
        ' aja ':' saja ',
        ' sj ':' saja ',
        ' sm ':' sama',
        ' tp ':' tapi ',
        ' lbh ':' lebih ',
        ' gajadi ':' tidak jadi ',
        ' utk ':' untuk ',
        ' trus ':' terus ',
        ' sdh ':' sudah ',
        ' lo ':' kamu ',
        ' pinter ':' pintar ',
        ' kalo ':' kalau ',
        ' doang ':' saja ',
        ' ngomong ':' bicara ',
        ' cm ':' cuma '
        
		}